# get-php-runtime.ps1 - fetch the pinned portable PHP runtime for the desktop package.
#
# Pin: PHP 8.4.26 (NTS, x64, VS17). The plan guessed 8.3.x, but this repo's
# composer.lock requires PHP >= 8.4 (6 locked packages, e.g. symfony/string
# v8.0.11; the dev vendor/composer/platform_check.php enforces >= 8.4.0, which
# is why dev runs Herd php84). A staged build made with the 8.3.35 zip died at
# the artisan smoke with "dependencies require a PHP version >= 8.4.0", so the
# bundled runtime must be 8.4.x. 8.4.26 is the current 8.4 release whose
# SHA-256 is published in releases/sha256sum.txt, which this script verifies
# (archived builds have NO official hash on windows.php.net: archives
# checksum.sha256 404s, per-file .sha256 404s, the archives listing only ships
# a stale PHP 5.2-era sha1sum.txt). Update the pin deliberately, never float it.
#
# Cache: exits 0 immediately when desktop/runtime/php/php.exe already exists.
# The verified zip is kept at desktop/runtime/dl/ so re-extraction after a
# partial failure does not need another ~34 MB download.
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'  # PS 5.1: keeps Invoke-WebRequest fast

$ver = '8.4.26'
$file = "php-$ver-nts-Win32-vs17-x64"
$base = 'https://windows.php.net/downloads/releases'
$zipUrl = "$base/$file.zip"
$sumsUrl = "$base/sha256sum.txt"

$root = Split-Path $PSScriptRoot -Parent
$dest = Join-Path $root 'desktop\runtime\php'
$phpExe = Join-Path $dest 'php.exe'
if (Test-Path $phpExe) {
    Write-Host "Portable PHP already present at $dest - cache hit, nothing to do."
    exit 0
}

$dlDir = Join-Path $root 'desktop\runtime\dl'
New-Item -ItemType Directory -Force -Path $dest, $dlDir | Out-Null
$zip = Join-Path $dlDir "$file.zip"

if (Test-Path $zip) {
    Write-Host "Reusing cached download: $zip"
} else {
    Write-Host "Downloading $zipUrl"
    Invoke-WebRequest -Uri $zipUrl -OutFile $zip -UseBasicParsing
}

Write-Host "Fetching official SHA-256 list: $sumsUrl"
$sums = (Invoke-WebRequest -Uri $sumsUrl -UseBasicParsing).Content
$m = [regex]::Match($sums, '(?m)^([a-f0-9]{64})[ \t]+\*?' + [regex]::Escape("$file.zip") + '[ \t]*\r?$')
if (-not $m.Success) { throw "No published SHA-256 for $file.zip in $sumsUrl - does the pin still exist on windows.php.net?" }
$expected = $m.Groups[1].Value.ToLower()
$actual = (Get-FileHash -Path $zip -Algorithm SHA256).Hash.ToLower()
if ($actual -ne $expected) {
    # A poisoned cache must not brick every later run: drop it and fail loudly.
    Remove-Item -Path $zip -Force
    throw "SHA-256 mismatch for $file.zip (expected $expected, got $actual). Cached zip removed; re-run to download a fresh copy."
}
Write-Host "SHA-256 verified: $actual"

Write-Host "Extracting to $dest"
Expand-Archive -Path $zip -DestinationPath $dest -Force

# extension= lines only for modules that ship as DLLs in ext\ AND that the app
# needs (pdo_sqlite/sqlite3 for the DB, mbstring for escpos-php, curl+openssl
# for HTTP/TLS and Laravel encryption, fileinfo for uploads, zip, gd). json,
# ctype, tokenizer, xml, dom, pcre, zlib etc. are compiled-in in the Windows
# builds - an extension= line for those prints "already loaded" warnings on
# every PHP start (verified with `php.exe -n -m`).
$ini = @'
; Macaron portable PHP runtime - generated by scripts/get-php-runtime.ps1
extension_dir = "ext"
memory_limit = 256M
max_execution_time = 60
cgi.fix_pathinfo = 1
extension=pdo_sqlite
extension=sqlite3
extension=mbstring
extension=curl
extension=openssl
extension=fileinfo
extension=zip
extension=gd
date.timezone = Asia/Karachi
'@
Set-Content -Path (Join-Path $dest 'php.ini') -Value $ini -Encoding Ascii

& $phpExe -r "exit((int) !(extension_loaded('pdo_sqlite') && extension_loaded('sqlite3') && extension_loaded('mbstring') && extension_loaded('curl') && extension_loaded('openssl') && extension_loaded('fileinfo') && extension_loaded('zip') && extension_loaded('gd')));"
if ($LASTEXITCODE -ne 0) { throw "php.exe smoke failed: required extensions missing (exit $LASTEXITCODE)" }
& $phpExe -v
if ($LASTEXITCODE -ne 0) { throw "php.exe -v failed (exit $LASTEXITCODE)" }
Write-Host "Portable PHP runtime ready at $dest"
